name: cli_code

on:
  push:
    branches: 
      - dev
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    
    
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
      
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
        # args: ". --check  -l 100   --verbose "
        args: ".   -l 100   --verbose "
     
#    - name: Pyflakes Syntax Checker
#      uses: lgeiger/pyflakes-action@v1.0.1
    
    
    - name: Install flake8
      run: pip install flake8
    
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'build'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

